// Generated by pnpm db:types from the migrated PostgreSQL catalog. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
export type Database = {
  public: {
    Tables: {
      audit_events: {
        Row: {
          id: string;
          actor_member_id: string | null;
          event_type: string;
          subject_id: string | null;
          details: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_member_id?: string | null;
          event_type: string;
          subject_id?: string | null;
          details?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_member_id?: string | null;
          event_type?: string;
          subject_id?: string | null;
          details?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_events_actor_member_id_fkey";
            columns: ["actor_member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      chain_operations: {
        Row: {
          id: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id: number;
          contract_address: string;
          recipient_address: string;
          issuance_key: string;
          status: Database["public"]["Enums"]["operation_status"];
          issuer_address: string | null;
          nonce: number | null;
          signed_transaction: string | null;
          transaction_hash: string | null;
          token_id: string | null;
          receipt_block: string | null;
          receipt_block_hash: string | null;
          last_error_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id?: number;
          contract_address: string;
          recipient_address: string;
          issuance_key: string;
          status?: Database["public"]["Enums"]["operation_status"];
          issuer_address?: string | null;
          nonce?: number | null;
          signed_transaction?: string | null;
          transaction_hash?: string | null;
          token_id?: string | null;
          receipt_block?: string | null;
          receipt_block_hash?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          wallet_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          recipient_address?: string;
          issuance_key?: string;
          status?: Database["public"]["Enums"]["operation_status"];
          issuer_address?: string | null;
          nonce?: number | null;
          signed_transaction?: string | null;
          transaction_hash?: string | null;
          token_id?: string | null;
          receipt_block?: string | null;
          receipt_block_hash?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chain_operations_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chain_operations_wallet_binding_id_member_id_fkey";
            columns: ["wallet_binding_id", "member_id"];
            isOneToOne: false;
            referencedRelation: "wallet_bindings";
            referencedColumns: ["id", "member_id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          token_hash: string;
          email: string;
          created_at: string;
          expires_at: string;
          revoked_at: string | null;
          redeemed_at: string | null;
          redeemed_by: string | null;
          last_otp_at: string | null;
          otp_requests: number;
        };
        Insert: {
          id?: string;
          token_hash: string;
          email: string;
          created_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          redeemed_at?: string | null;
          redeemed_by?: string | null;
          last_otp_at?: string | null;
          otp_requests?: number;
        };
        Update: {
          id?: string;
          token_hash?: string;
          email?: string;
          created_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          redeemed_at?: string | null;
          redeemed_by?: string | null;
          last_otp_at?: string | null;
          otp_requests?: number;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_redeemed_by_fkey";
            columns: ["redeemed_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      issuer_nonces: {
        Row: {
          chain_id: number;
          issuer_address: string;
          next_nonce: number;
          updated_at: string;
        };
        Insert: {
          chain_id: number;
          issuer_address: string;
          next_nonce: number;
          updated_at?: string;
        };
        Update: {
          chain_id?: number;
          issuer_address?: string;
          next_nonce?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      member_roles: {
        Row: {
          member_id: string;
          role: Database["public"]["Enums"]["member_role"];
          granted_by: string | null;
          created_at: string;
        };
        Insert: {
          member_id: string;
          role: Database["public"]["Enums"]["member_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Update: {
          member_id?: string;
          role?: Database["public"]["Enums"]["member_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "member_roles_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "member_roles_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      members: {
        Row: {
          id: string;
          auth_user_id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          email?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      membership_bindings: {
        Row: {
          id: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          verified_block: string;
          verified_block_hash: string;
          mint_operation_id: string | null;
          bound_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id?: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          verified_block: string;
          verified_block_hash: string;
          mint_operation_id?: string | null;
          bound_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          wallet_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          token_id?: string;
          ownership_epoch?: string;
          verified_block?: string;
          verified_block_hash?: string;
          mint_operation_id?: string | null;
          bound_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "membership_bindings_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "membership_bindings_mint_operation_id_fkey";
            columns: ["mint_operation_id"];
            isOneToOne: false;
            referencedRelation: "chain_operations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "membership_bindings_wallet_binding_id_member_id_fkey";
            columns: ["wallet_binding_id", "member_id"];
            isOneToOne: false;
            referencedRelation: "wallet_bindings";
            referencedColumns: ["id", "member_id"];
          },
        ];
      };
      promotion_decisions: {
        Row: {
          id: string;
          member_id: string;
          membership_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          tier: string;
          approved_by: string;
          rationale: string;
          evidence: Json;
          approved_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          membership_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          tier?: string;
          approved_by: string;
          rationale: string;
          evidence: Json;
          approved_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          membership_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          token_id?: string;
          ownership_epoch?: string;
          tier?: string;
          approved_by?: string;
          rationale?: string;
          evidence?: Json;
          approved_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "promotion_decisions_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "promotion_decisions_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "promotion_decisions_membership_binding_id_member_id_chain__fkey";
            columns: [
              "membership_binding_id",
              "member_id",
              "chain_id",
              "contract_address",
              "token_id",
              "ownership_epoch",
            ];
            isOneToOne: false;
            referencedRelation: "membership_bindings";
            referencedColumns: [
              "id",
              "member_id",
              "chain_id",
              "contract_address",
              "token_id",
              "ownership_epoch",
            ];
          },
        ];
      };
      wallet_bindings: {
        Row: {
          id: string;
          member_id: string;
          address: string;
          chain_id: number;
          challenge_id: string;
          verified_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          address: string;
          chain_id?: number;
          challenge_id: string;
          verified_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          address?: string;
          chain_id?: number;
          challenge_id?: string;
          verified_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "wallet_bindings_challenge_id_member_id_address_chain_id_fkey";
            columns: ["challenge_id", "member_id", "address", "chain_id"];
            isOneToOne: false;
            referencedRelation: "wallet_challenges";
            referencedColumns: ["id", "member_id", "address", "chain_id"];
          },
          {
            foreignKeyName: "wallet_bindings_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      wallet_challenges: {
        Row: {
          id: string;
          member_id: string;
          address: string;
          nonce: string;
          domain: string;
          uri: string;
          chain_id: number;
          message: string;
          created_at: string;
          expires_at: string;
          consumed_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          address: string;
          nonce: string;
          domain: string;
          uri: string;
          chain_id?: number;
          message: string;
          created_at?: string;
          expires_at: string;
          consumed_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          address?: string;
          nonce?: string;
          domain?: string;
          uri?: string;
          chain_id?: number;
          message?: string;
          created_at?: string;
          expires_at?: string;
          consumed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "wallet_challenges_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: {
      member_role: "reviewer" | "steward" | "issuer";
      operation_status:
        "created" | "signed" | "broadcast" | "confirmed" | "reverted";
    };
    CompositeTypes: Record<never, never>;
  };
};
