// Generated by pnpm db:types from the migrated PostgreSQL catalog. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
export type Database = {
  public: {
    Tables: {
      alpha_award_authorizations: {
        Row: {
          category: string;
          approved_by: string;
          policy_evidence: string;
          created_at: string;
        };
        Insert: {
          category: string;
          approved_by: string;
          policy_evidence: string;
          created_at?: string;
        };
        Update: {
          category?: string;
          approved_by?: string;
          policy_evidence?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_award_authorizations_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      alpha_credit_states: {
        Row: {
          version_id: string;
          status: string;
        };
        Insert: {
          version_id: string;
          status: string;
        };
        Update: {
          version_id?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_credit_states_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: true;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      alpha_feedback: {
        Row: {
          id: string;
          version_id: string;
          member_id: string;
          request_id: string;
          kind: string;
          detail: string;
          source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          version_id: string;
          member_id: string;
          request_id: string;
          kind: string;
          detail: string;
          source: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          version_id?: string;
          member_id?: string;
          request_id?: string;
          kind?: string;
          detail?: string;
          source?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_feedback_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_feedback_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "alpha_versions";
            referencedColumns: ["version_id"];
          },
        ];
      };
      alpha_outcomes: {
        Row: {
          id: string;
          version_id: string;
          actor_id: string;
          status: string;
          facts: string;
          sources: Json;
          checked_at: string;
        };
        Insert: {
          id?: string;
          version_id: string;
          actor_id: string;
          status: string;
          facts: string;
          sources: Json;
          checked_at?: string;
        };
        Update: {
          id?: string;
          version_id?: string;
          actor_id?: string;
          status?: string;
          facts?: string;
          sources?: Json;
          checked_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_outcomes_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_outcomes_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "alpha_versions";
            referencedColumns: ["version_id"];
          },
        ];
      };
      alpha_preliminary_runs: {
        Row: {
          id: string;
          version_id: string;
          requested_by: string;
          status: string;
          provider: string | null;
          model: string | null;
          error_code: string | null;
          card: Json | null;
          sources: Json;
          checks: Json;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          version_id: string;
          requested_by: string;
          status?: string;
          provider?: string | null;
          model?: string | null;
          error_code?: string | null;
          card?: Json | null;
          sources?: Json;
          checks?: Json;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          version_id?: string;
          requested_by?: string;
          status?: string;
          provider?: string | null;
          model?: string | null;
          error_code?: string | null;
          card?: Json | null;
          sources?: Json;
          checks?: Json;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_preliminary_runs_requested_by_fkey";
            columns: ["requested_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_preliminary_runs_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "alpha_versions";
            referencedColumns: ["version_id"];
          },
        ];
      };
      alpha_requests: {
        Row: {
          member_id: string;
          request_id: string;
          payload: Json;
          finding_id: string;
          version_id: string;
        };
        Insert: {
          member_id: string;
          request_id: string;
          payload: Json;
          finding_id: string;
          version_id: string;
        };
        Update: {
          member_id?: string;
          request_id?: string;
          payload?: Json;
          finding_id?: string;
          version_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_requests_finding_id_fkey";
            columns: ["finding_id"];
            isOneToOne: false;
            referencedRelation: "findings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_requests_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_requests_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      alpha_reviewer_scopes: {
        Row: {
          member_id: string;
          category: string;
          scope: string;
          granted_by: string;
          created_at: string;
        };
        Insert: {
          member_id: string;
          category: string;
          scope: string;
          granted_by: string;
          created_at?: string;
        };
        Update: {
          member_id?: string;
          category?: string;
          scope?: string;
          granted_by?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_reviewer_scopes_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "alpha_reviewer_scopes_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      alpha_versions: {
        Row: {
          version_id: string;
          category: string;
          contribution_type: string;
          purpose: string;
          subject: string;
          chain: string;
          contract: string;
          details: Json;
          evidence: Json;
          first_noticed: string | null;
          horizon: string | null;
          check_condition: string;
          source_created_at: string | null;
          created_at: string;
        };
        Insert: {
          version_id: string;
          category: string;
          contribution_type: string;
          purpose: string;
          subject: string;
          chain?: string;
          contract?: string;
          details: Json;
          evidence: Json;
          first_noticed?: string | null;
          horizon?: string | null;
          check_condition?: string;
          source_created_at?: string | null;
          created_at?: string;
        };
        Update: {
          version_id?: string;
          category?: string;
          contribution_type?: string;
          purpose?: string;
          subject?: string;
          chain?: string;
          contract?: string;
          details?: Json;
          evidence?: Json;
          first_noticed?: string | null;
          horizon?: string | null;
          check_condition?: string;
          source_created_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "alpha_versions_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: true;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_events: {
        Row: {
          id: string;
          actor_member_id: string | null;
          event_type: string;
          subject_id: string | null;
          details: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_member_id?: string | null;
          event_type: string;
          subject_id?: string | null;
          details?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_member_id?: string | null;
          event_type?: string;
          subject_id?: string | null;
          details?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_events_actor_member_id_fkey";
            columns: ["actor_member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      award_ledger: {
        Row: {
          id: string;
          finding_id: string;
          version_id: string;
          member_id: string;
          decision_id: string;
          xp: number;
          points: number;
          season: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          finding_id: string;
          version_id: string;
          member_id: string;
          decision_id: string;
          xp: number;
          points: number;
          season: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          finding_id?: string;
          version_id?: string;
          member_id?: string;
          decision_id?: string;
          xp?: number;
          points?: number;
          season?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "award_ledger_decision_id_fkey";
            columns: ["decision_id"];
            isOneToOne: true;
            referencedRelation: "review_decisions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "award_ledger_finding_id_fkey";
            columns: ["finding_id"];
            isOneToOne: true;
            referencedRelation: "findings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "award_ledger_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "award_ledger_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      chain_operations: {
        Row: {
          id: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id: number;
          contract_address: string;
          recipient_address: string;
          issuance_key: string;
          status: Database["public"]["Enums"]["operation_status"];
          issuer_address: string | null;
          nonce: number | null;
          signed_transaction: string | null;
          transaction_hash: string | null;
          token_id: string | null;
          receipt_block: string | null;
          receipt_block_hash: string | null;
          last_error_code: string | null;
          created_at: string;
          updated_at: string;
          binding_completed_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id?: number;
          contract_address: string;
          recipient_address: string;
          issuance_key: string;
          status?: Database["public"]["Enums"]["operation_status"];
          issuer_address?: string | null;
          nonce?: number | null;
          signed_transaction?: string | null;
          transaction_hash?: string | null;
          token_id?: string | null;
          receipt_block?: string | null;
          receipt_block_hash?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
          binding_completed_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          wallet_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          recipient_address?: string;
          issuance_key?: string;
          status?: Database["public"]["Enums"]["operation_status"];
          issuer_address?: string | null;
          nonce?: number | null;
          signed_transaction?: string | null;
          transaction_hash?: string | null;
          token_id?: string | null;
          receipt_block?: string | null;
          receipt_block_hash?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
          binding_completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "chain_operations_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chain_operations_wallet_binding_id_member_id_fkey";
            columns: ["wallet_binding_id", "member_id"];
            isOneToOne: false;
            referencedRelation: "wallet_bindings";
            referencedColumns: ["id", "member_id"];
          },
        ];
      };
      chat_media: {
        Row: {
          id: string;
          member_id: string;
          room_id: string;
          message_id: string | null;
          content_type: string;
          content_base64: string;
          byte_size: number;
          created_at: string;
        };
        Insert: {
          id: string;
          member_id: string;
          room_id: string;
          message_id?: string | null;
          content_type: string;
          content_base64: string;
          byte_size: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          room_id?: string;
          message_id?: string | null;
          content_type?: string;
          content_base64?: string;
          byte_size?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_media_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_media_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "discussion_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_media_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_reactions: {
        Row: {
          message_id: string;
          member_id: string;
          emoji: string;
          created_at: string;
        };
        Insert: {
          message_id: string;
          member_id: string;
          emoji: string;
          created_at?: string;
        };
        Update: {
          message_id?: string;
          member_id?: string;
          emoji?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_reactions_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_reactions_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "discussion_messages";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_reads: {
        Row: {
          member_id: string;
          room_id: string;
          last_sequence: number;
        };
        Insert: {
          member_id: string;
          room_id: string;
          last_sequence?: number;
        };
        Update: {
          member_id?: string;
          room_id?: string;
          last_sequence?: number;
        };
        Relationships: [
          {
            foreignKeyName: "chat_reads_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_reads_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_requests: {
        Row: {
          member_id: string;
          request_id: string;
          payload: Json;
          result: Json;
        };
        Insert: {
          member_id: string;
          request_id: string;
          payload: Json;
          result: Json;
        };
        Update: {
          member_id?: string;
          request_id?: string;
          payload?: Json;
          result?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "chat_requests_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_revisions: {
        Row: {
          id: string;
          message_id: string;
          author_id: string;
          body: string;
          attachments: Json;
          deleted: boolean;
          created_at: string;
          sequence: number;
        };
        Insert: {
          id?: string;
          message_id: string;
          author_id: string;
          body: string;
          attachments?: Json;
          deleted?: boolean;
          created_at?: string;
          sequence: number;
        };
        Update: {
          id?: string;
          message_id?: string;
          author_id?: string;
          body?: string;
          attachments?: Json;
          deleted?: boolean;
          created_at?: string;
          sequence?: number;
        };
        Relationships: [
          {
            foreignKeyName: "chat_revisions_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_revisions_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "discussion_messages";
            referencedColumns: ["id"];
          },
        ];
      };
      discussion_messages: {
        Row: {
          id: string;
          question_id: string;
          author_id: string;
          specialty: string;
          body: string;
          sources: Json;
          reply_to: string | null;
          created_at: string;
          sequence: number;
        };
        Insert: {
          id?: string;
          question_id: string;
          author_id: string;
          specialty: string;
          body: string;
          sources?: Json;
          reply_to?: string | null;
          created_at?: string;
          sequence: number;
        };
        Update: {
          id?: string;
          question_id?: string;
          author_id?: string;
          specialty?: string;
          body?: string;
          sources?: Json;
          reply_to?: string | null;
          created_at?: string;
          sequence?: number;
        };
        Relationships: [
          {
            foreignKeyName: "discussion_messages_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "discussion_messages_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "discussion_messages_reply_to_fkey";
            columns: ["reply_to"];
            isOneToOne: false;
            referencedRelation: "discussion_messages";
            referencedColumns: ["id"];
          },
        ];
      };
      finding_disputes: {
        Row: {
          id: string;
          version_id: string;
          member_id: string;
          reason: string;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          version_id: string;
          member_id: string;
          reason: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          version_id?: string;
          member_id?: string;
          reason?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "finding_disputes_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_disputes_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      finding_usefulness: {
        Row: {
          id: string;
          version_id: string;
          member_id: string;
          specialty: string;
          detail: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          version_id: string;
          member_id: string;
          specialty: string;
          detail: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          version_id?: string;
          member_id?: string;
          specialty?: string;
          detail?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "finding_usefulness_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_usefulness_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      finding_versions: {
        Row: {
          id: string;
          finding_id: string;
          version: number;
          previous_version: string | null;
          specialty: string;
          claim: string;
          sources: Json;
          addition: string;
          limitations: string;
          source_message: string | null;
          related_version: string | null;
          correction: string | null;
          observed_at: string;
          submitted_at: string;
          source_revision: string | null;
        };
        Insert: {
          id?: string;
          finding_id: string;
          version: number;
          previous_version?: string | null;
          specialty: string;
          claim: string;
          sources: Json;
          addition: string;
          limitations: string;
          source_message?: string | null;
          related_version?: string | null;
          correction?: string | null;
          observed_at: string;
          submitted_at?: string;
          source_revision?: string | null;
        };
        Update: {
          id?: string;
          finding_id?: string;
          version?: number;
          previous_version?: string | null;
          specialty?: string;
          claim?: string;
          sources?: Json;
          addition?: string;
          limitations?: string;
          source_message?: string | null;
          related_version?: string | null;
          correction?: string | null;
          observed_at?: string;
          submitted_at?: string;
          source_revision?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "finding_versions_finding_id_fkey";
            columns: ["finding_id"];
            isOneToOne: false;
            referencedRelation: "findings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_versions_previous_version_fkey";
            columns: ["previous_version"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_versions_related_version_fkey";
            columns: ["related_version"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_versions_source_message_fkey";
            columns: ["source_message"];
            isOneToOne: false;
            referencedRelation: "discussion_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "finding_versions_source_revision_fkey";
            columns: ["source_revision"];
            isOneToOne: false;
            referencedRelation: "chat_revisions";
            referencedColumns: ["id"];
          },
        ];
      };
      findings: {
        Row: {
          id: string;
          question_id: string;
          author_id: string;
          visibility: string;
          current_version: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          question_id: string;
          author_id: string;
          visibility: string;
          current_version?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          question_id?: string;
          author_id?: string;
          visibility?: string;
          current_version?: string | null;
          status?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "current_version_belongs_to_finding";
            columns: ["id", "current_version"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["finding_id", "id"];
          },
          {
            foreignKeyName: "findings_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "findings_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          token_hash: string;
          email: string;
          created_at: string;
          expires_at: string;
          revoked_at: string | null;
          redeemed_at: string | null;
          redeemed_by: string | null;
          last_otp_at: string | null;
          otp_requests: number;
        };
        Insert: {
          id?: string;
          token_hash: string;
          email: string;
          created_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          redeemed_at?: string | null;
          redeemed_by?: string | null;
          last_otp_at?: string | null;
          otp_requests?: number;
        };
        Update: {
          id?: string;
          token_hash?: string;
          email?: string;
          created_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          redeemed_at?: string | null;
          redeemed_by?: string | null;
          last_otp_at?: string | null;
          otp_requests?: number;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_redeemed_by_fkey";
            columns: ["redeemed_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      issuer_nonces: {
        Row: {
          chain_id: number;
          issuer_address: string;
          next_nonce: number;
          updated_at: string;
        };
        Insert: {
          chain_id: number;
          issuer_address: string;
          next_nonce: number;
          updated_at?: string;
        };
        Update: {
          chain_id?: number;
          issuer_address?: string;
          next_nonce?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      member_activity: {
        Row: {
          id: string;
          member_id: string;
          finding_id: string;
          kind: string;
          record_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          finding_id: string;
          kind: string;
          record_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          finding_id?: string;
          kind?: string;
          record_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "member_activity_finding_id_fkey";
            columns: ["finding_id"];
            isOneToOne: false;
            referencedRelation: "findings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "member_activity_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      member_roles: {
        Row: {
          member_id: string;
          role: Database["public"]["Enums"]["member_role"];
          granted_by: string | null;
          created_at: string;
        };
        Insert: {
          member_id: string;
          role: Database["public"]["Enums"]["member_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Update: {
          member_id?: string;
          role?: Database["public"]["Enums"]["member_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "member_roles_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "member_roles_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      members: {
        Row: {
          id: string;
          auth_user_id: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          email?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      membership_bindings: {
        Row: {
          id: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          verified_block: string;
          verified_block_hash: string;
          mint_operation_id: string | null;
          bound_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          wallet_binding_id: string;
          chain_id?: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          verified_block: string;
          verified_block_hash: string;
          mint_operation_id?: string | null;
          bound_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          wallet_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          token_id?: string;
          ownership_epoch?: string;
          verified_block?: string;
          verified_block_hash?: string;
          mint_operation_id?: string | null;
          bound_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "membership_bindings_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "membership_bindings_mint_operation_id_fkey";
            columns: ["mint_operation_id"];
            isOneToOne: false;
            referencedRelation: "chain_operations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "membership_bindings_wallet_binding_id_member_id_fkey";
            columns: ["wallet_binding_id", "member_id"];
            isOneToOne: false;
            referencedRelation: "wallet_bindings";
            referencedColumns: ["id", "member_id"];
          },
        ];
      };
      nft_acquisition_events: {
        Row: {
          id: string;
          binding_id: string;
          kind: string;
          evidence: string | null;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          binding_id: string;
          kind: string;
          evidence?: string | null;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          binding_id?: string;
          kind?: string;
          evidence?: string | null;
          recorded_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "nft_acquisition_events_binding_id_fkey";
            columns: ["binding_id"];
            isOneToOne: true;
            referencedRelation: "membership_bindings";
            referencedColumns: ["id"];
          },
        ];
      };
      nft_tier_events: {
        Row: {
          id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          tier: string;
          promotion_id: string;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          tier: string;
          promotion_id: string;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          chain_id?: number;
          contract_address?: string;
          token_id?: string;
          tier?: string;
          promotion_id?: string;
          recorded_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "nft_tier_events_promotion_id_fkey";
            columns: ["promotion_id"];
            isOneToOne: true;
            referencedRelation: "promotion_decisions";
            referencedColumns: ["id"];
          },
        ];
      };
      opportunities: {
        Row: {
          id: string;
          name: string;
          description: string;
          kind: string;
          eligible_ranks: Json;
          requirements: string;
          approval_required: boolean;
          status: string;
          starts_at: string | null;
          ends_at: string | null;
          public_visible: boolean;
          action_type: string;
          protected_url: string | null;
          claim_active: boolean;
          is_demo: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          kind: string;
          eligible_ranks: Json;
          requirements?: string;
          approval_required?: boolean;
          status?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          public_visible?: boolean;
          action_type: string;
          protected_url?: string | null;
          claim_active?: boolean;
          is_demo?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          kind?: string;
          eligible_ranks?: Json;
          requirements?: string;
          approval_required?: boolean;
          status?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          public_visible?: boolean;
          action_type?: string;
          protected_url?: string | null;
          claim_active?: boolean;
          is_demo?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "opportunities_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      opportunity_registrations: {
        Row: {
          opportunity_id: string;
          member_id: string;
          status: string;
          created_at: string;
        };
        Insert: {
          opportunity_id: string;
          member_id: string;
          status: string;
          created_at?: string;
        };
        Update: {
          opportunity_id?: string;
          member_id?: string;
          status?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "opportunity_registrations_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunity_registrations_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
        ];
      };
      opportunity_requirements: {
        Row: {
          opportunity_id: string;
          member_id: string;
          approved: boolean;
          reason: string;
          assessed_by: string;
          updated_at: string;
          verified_requirements: string | null;
        };
        Insert: {
          opportunity_id: string;
          member_id: string;
          approved: boolean;
          reason: string;
          assessed_by: string;
          updated_at?: string;
          verified_requirements?: string | null;
        };
        Update: {
          opportunity_id?: string;
          member_id?: string;
          approved?: boolean;
          reason?: string;
          assessed_by?: string;
          updated_at?: string;
          verified_requirements?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "opportunity_requirements_assessed_by_fkey";
            columns: ["assessed_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunity_requirements_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "opportunity_requirements_opportunity_id_fkey";
            columns: ["opportunity_id"];
            isOneToOne: false;
            referencedRelation: "opportunities";
            referencedColumns: ["id"];
          },
        ];
      };
      peer_requests: {
        Row: {
          id: string;
          member_id: string;
          question_id: string;
          specialty: string;
          request: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          question_id: string;
          specialty: string;
          request: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          question_id?: string;
          specialty?: string;
          request?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "peer_requests_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "peer_requests_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      promotion_decisions: {
        Row: {
          id: string;
          member_id: string;
          membership_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          tier: string;
          approved_by: string;
          rationale: string;
          evidence: Json;
          approved_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          membership_binding_id: string;
          chain_id: number;
          contract_address: string;
          token_id: string;
          ownership_epoch: string;
          tier?: string;
          approved_by: string;
          rationale: string;
          evidence: Json;
          approved_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          membership_binding_id?: string;
          chain_id?: number;
          contract_address?: string;
          token_id?: string;
          ownership_epoch?: string;
          tier?: string;
          approved_by?: string;
          rationale?: string;
          evidence?: Json;
          approved_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "promotion_decisions_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "promotion_decisions_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "promotion_decisions_membership_binding_id_member_id_chain__fkey";
            columns: [
              "membership_binding_id",
              "member_id",
              "chain_id",
              "contract_address",
              "token_id",
              "ownership_epoch",
            ];
            isOneToOne: false;
            referencedRelation: "membership_bindings";
            referencedColumns: [
              "id",
              "member_id",
              "chain_id",
              "contract_address",
              "token_id",
              "ownership_epoch",
            ];
          },
        ];
      };
      rank_demo_delegations: {
        Row: {
          id: string;
          delegate_id: string;
          owner_id: string;
          status: string;
          nft_xp: number;
        };
        Insert: {
          id: string;
          delegate_id: string;
          owner_id: string;
          status: string;
          nft_xp: number;
        };
        Update: {
          id?: string;
          delegate_id?: string;
          owner_id?: string;
          status?: string;
          nft_xp?: number;
        };
        Relationships: [
          {
            foreignKeyName: "rank_demo_delegations_delegate_id_fkey";
            columns: ["delegate_id"];
            isOneToOne: false;
            referencedRelation: "rank_demo_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rank_demo_delegations_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "rank_demo_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      rank_demo_messages: {
        Row: {
          id: string;
          question_id: string;
          author_id: string;
          body: string;
          reply_to: string | null;
          delegation_id: string | null;
          sequence: number;
        };
        Insert: {
          id: string;
          question_id: string;
          author_id: string;
          body: string;
          reply_to?: string | null;
          delegation_id?: string | null;
          sequence: number;
        };
        Update: {
          id?: string;
          question_id?: string;
          author_id?: string;
          body?: string;
          reply_to?: string | null;
          delegation_id?: string | null;
          sequence?: number;
        };
        Relationships: [
          {
            foreignKeyName: "rank_demo_messages_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "rank_demo_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rank_demo_messages_delegation_id_fkey";
            columns: ["delegation_id"];
            isOneToOne: false;
            referencedRelation: "rank_demo_delegations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rank_demo_messages_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "research_questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rank_demo_messages_reply_to_fkey";
            columns: ["reply_to"];
            isOneToOne: false;
            referencedRelation: "rank_demo_messages";
            referencedColumns: ["id"];
          },
        ];
      };
      rank_demo_profiles: {
        Row: {
          id: string;
          name: string;
          rank: string;
          specialty: string;
          bio: string;
          personal_xp: number;
          acquisition: string;
        };
        Insert: {
          id: string;
          name: string;
          rank: string;
          specialty: string;
          bio: string;
          personal_xp: number;
          acquisition: string;
        };
        Update: {
          id?: string;
          name?: string;
          rank?: string;
          specialty?: string;
          bio?: string;
          personal_xp?: number;
          acquisition?: string;
        };
        Relationships: [];
      };
      research_assignment: {
        Row: {
          id: boolean;
          funder: string;
          deliverable: string;
          terms: string;
          rights: string;
          dispute_route: string;
          compensation: string;
          funding_status: string;
          assignee_id: string | null;
          version_id: string | null;
          work_status: string;
          payment_status: string;
        };
        Insert: {
          id?: boolean;
          funder: string;
          deliverable: string;
          terms: string;
          rights: string;
          dispute_route: string;
          compensation: string;
          funding_status: string;
          assignee_id?: string | null;
          version_id?: string | null;
          work_status?: string;
          payment_status?: string;
        };
        Update: {
          id?: boolean;
          funder?: string;
          deliverable?: string;
          terms?: string;
          rights?: string;
          dispute_route?: string;
          compensation?: string;
          funding_status?: string;
          assignee_id?: string | null;
          version_id?: string | null;
          work_status?: string;
          payment_status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "research_assignment_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "research_assignment_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      research_policy: {
        Row: {
          id: boolean;
          acceptance_xp: number;
          acceptance_points: number;
          season: string;
          silver_xp: number;
          silver_findings: number;
          silver_uses: number;
        };
        Insert: {
          id?: boolean;
          acceptance_xp?: number;
          acceptance_points?: number;
          season?: string;
          silver_xp?: number;
          silver_findings?: number;
          silver_uses?: number;
        };
        Update: {
          id?: boolean;
          acceptance_xp?: number;
          acceptance_points?: number;
          season?: string;
          silver_xp?: number;
          silver_findings?: number;
          silver_uses?: number;
        };
        Relationships: [];
      };
      research_profiles: {
        Row: {
          member_id: string;
          display_name: string;
          specialty: string;
          updated_at: string;
          is_demo: boolean;
          bio: string;
          interest: string;
        };
        Insert: {
          member_id: string;
          display_name: string;
          specialty: string;
          updated_at?: string;
          is_demo?: boolean;
          bio?: string;
          interest?: string;
        };
        Update: {
          member_id?: string;
          display_name?: string;
          specialty?: string;
          updated_at?: string;
          is_demo?: boolean;
          bio?: string;
          interest?: string;
        };
        Relationships: [
          {
            foreignKeyName: "research_profiles_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: true;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      research_questions: {
        Row: {
          id: string;
          title: string;
          purpose: string;
          gaps: Json;
          rank: string;
          category: string;
        };
        Insert: {
          id: string;
          title: string;
          purpose: string;
          gaps: Json;
          rank?: string;
          category?: string;
        };
        Update: {
          id?: string;
          title?: string;
          purpose?: string;
          gaps?: Json;
          rank?: string;
          category?: string;
        };
        Relationships: [];
      };
      research_reviewer_scopes: {
        Row: {
          member_id: string;
          specialty: string;
          scope: string;
          granted_by: string;
        };
        Insert: {
          member_id: string;
          specialty: string;
          scope: string;
          granted_by: string;
        };
        Update: {
          member_id?: string;
          specialty?: string;
          scope?: string;
          granted_by?: string;
        };
        Relationships: [
          {
            foreignKeyName: "research_reviewer_scopes_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "research_reviewer_scopes_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      review_assignments: {
        Row: {
          id: string;
          version_id: string;
          reviewer_id: string;
          scope: string;
          kind: string;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          version_id: string;
          reviewer_id: string;
          scope: string;
          kind?: string;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          version_id?: string;
          reviewer_id?: string;
          scope?: string;
          kind?: string;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "review_assignments_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "review_assignments_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      review_decisions: {
        Row: {
          id: string;
          assignment_id: string;
          version_id: string;
          reviewer_id: string;
          decision: string;
          reason: string;
          conflicts: string;
          scope: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          assignment_id: string;
          version_id: string;
          reviewer_id: string;
          decision: string;
          reason: string;
          conflicts: string;
          scope: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          assignment_id?: string;
          version_id?: string;
          reviewer_id?: string;
          decision?: string;
          reason?: string;
          conflicts?: string;
          scope?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "review_decisions_assignment_id_fkey";
            columns: ["assignment_id"];
            isOneToOne: true;
            referencedRelation: "review_assignments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "review_decisions_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "review_decisions_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "finding_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      wallet_bindings: {
        Row: {
          id: string;
          member_id: string;
          address: string;
          chain_id: number;
          challenge_id: string;
          verified_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          address: string;
          chain_id?: number;
          challenge_id: string;
          verified_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          address?: string;
          chain_id?: number;
          challenge_id?: string;
          verified_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "wallet_bindings_challenge_id_member_id_address_chain_id_fkey";
            columns: ["challenge_id", "member_id", "address", "chain_id"];
            isOneToOne: false;
            referencedRelation: "wallet_challenges";
            referencedColumns: ["id", "member_id", "address", "chain_id"];
          },
          {
            foreignKeyName: "wallet_bindings_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      wallet_challenges: {
        Row: {
          id: string;
          member_id: string;
          address: string;
          nonce: string;
          domain: string;
          uri: string;
          chain_id: number;
          message: string;
          created_at: string;
          expires_at: string;
          consumed_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          address: string;
          nonce: string;
          domain: string;
          uri: string;
          chain_id?: number;
          message: string;
          created_at?: string;
          expires_at: string;
          consumed_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          address?: string;
          nonce?: string;
          domain?: string;
          uri?: string;
          chain_id?: number;
          message?: string;
          created_at?: string;
          expires_at?: string;
          consumed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "wallet_challenges_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<never, never>;
    Functions: {
      allocate_mint_nonce: {
        Args: {
          p_operation: string;
          p_issuer: string;
          p_pending: number;
        };
        Returns: number;
      };
      alpha_add_feedback: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
          p_request: string;
          p_kind: string;
          p_detail: string;
          p_source: string;
        };
        Returns: string;
      };
      alpha_appeal: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
          p_reason: string;
        };
        Returns: string;
      };
      alpha_authorized_reviewer: {
        Args: {
          p_member: string;
          p_version: string;
          p_scope: string;
        };
        Returns: boolean;
      };
      alpha_begin_review: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
        };
        Returns: Json;
      };
      alpha_decide: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
          p_assignment: string;
          p_decision: string;
          p_reason: string;
          p_conflicts: string;
          p_conflict_free: boolean;
        };
        Returns: Json;
      };
      alpha_finish_review: {
        Args: {
          p_id: string;
          p_status: string;
          p_provider?: string;
          p_model?: string;
          p_card?: Json;
          p_sources?: Json;
          p_checks?: Json;
          p_error?: string;
        };
        Returns: undefined;
      };
      alpha_media_read: {
        Args: {
          p_member: string;
          p_binding: string;
          p_id: string;
          p_version: string;
        };
        Returns: Json;
      };
      alpha_record_outcome: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
          p_status: string;
          p_facts: string;
          p_sources: Json;
        };
        Returns: string;
      };
      alpha_snapshot: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      alpha_snapshot_base: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      alpha_submit: {
        Args: {
          p_member: string;
          p_binding: string;
          p_request: string;
          p_data: Json;
        };
        Returns: Json;
      };
      alpha_version_guard: {
        Args: {
          p_member: string;
          p_binding: string;
          p_version: string;
        };
        Returns: Json;
      };
      bind_owned_token: {
        Args: {
          p_member: string;
          p_contract: string;
          p_token: string;
          p_epoch: string;
          p_block: string;
          p_hash: string;
          p_mint?: string;
        };
        Returns: string;
      };
      bind_verified_wallet: {
        Args: {
          p_member_id: string;
          p_challenge_id: string;
          p_message: string;
        };
        Returns: string;
      };
      chat_media_read: {
        Args: {
          p_member: string;
          p_binding: string;
          p_id: string;
        };
        Returns: Json;
      };
      chat_mutate: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room: string;
          p_request: string;
          p_action: string;
          p_data: Json;
        };
        Returns: Json;
      };
      chat_snapshot: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room: string;
          p_before?: number;
          p_after?: number;
        };
        Returns: Json;
      };
      chat_snapshot_base: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room: string;
          p_before?: number;
          p_after?: number;
        };
        Returns: Json;
      };
      chat_source_media_read: {
        Args: {
          p_member: string;
          p_binding: string;
          p_id: string;
          p_version: string;
        };
        Returns: Json;
      };
      chat_upload: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room: string;
          p_id: string;
          p_type: string;
          p_content: string;
          p_size: number;
        };
        Returns: Json;
      };
      create_mint_operation: {
        Args: {
          p_member: string;
          p_contract: string;
          p_key: string;
        };
        Returns: string;
      };
      issue_wallet_challenge: {
        Args: {
          p_id: string;
          p_member_id: string;
          p_address: string;
          p_nonce: string;
          p_domain: string;
          p_uri: string;
          p_message: string;
          p_created_at: string;
          p_expires_at: string;
        };
        Returns: string;
      };
      member_room_guard: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room: string;
        };
        Returns: undefined;
      };
      nft_tier: {
        Args: {
          p_contract: string;
          p_token: string;
        };
        Returns: string;
      };
      opportunity_action: {
        Args: {
          p_member: string;
          p_binding: string;
          p_id: string;
          p_action: string;
        };
        Returns: Json;
      };
      opportunity_action_base: {
        Args: {
          p_member: string;
          p_binding: string;
          p_id: string;
          p_action: string;
        };
        Returns: Json;
      };
      opportunity_list: {
        Args: {
          p_sample?: boolean;
        };
        Returns: Json;
      };
      opportunity_manage: {
        Args: {
          p_member: string;
          p_binding: string;
          p_action: string;
          p_data: Json;
        };
        Returns: Json;
      };
      persist_mint_transaction: {
        Args: {
          p_operation: string;
          p_signed: string;
          p_hash: string;
        };
        Returns: string;
      };
      redeem_invitation: {
        Args: {
          p_token_hash: string;
          p_auth_user_id: string;
        };
        Returns: string;
      };
      research_assign: {
        Args: {
          p_version: string;
          p_kind?: string;
        };
        Returns: undefined;
      };
      research_assign_pre_alpha: {
        Args: {
          p_version: string;
          p_kind?: string;
        };
        Returns: undefined;
      };
      research_assign_v2: {
        Args: {
          p_version: string;
          p_kind?: string;
        };
        Returns: undefined;
      };
      research_can_view: {
        Args: {
          p_member: string;
          p_finding: string;
        };
        Returns: boolean;
      };
      research_can_view_pre_alpha: {
        Args: {
          p_member: string;
          p_finding: string;
        };
        Returns: boolean;
      };
      research_can_view_v2: {
        Args: {
          p_member: string;
          p_finding: string;
        };
        Returns: boolean;
      };
      research_compatible: {
        Args: {
          p_actor: string;
          p_author: string;
        };
        Returns: boolean;
      };
      research_mutate: {
        Args: {
          p_member: string;
          p_action: string;
          p_data: Json;
        };
        Returns: Json;
      };
      research_mutate_v2: {
        Args: {
          p_member: string;
          p_binding: string;
          p_action: string;
          p_data: Json;
        };
        Returns: Json;
      };
      research_mutate_v3: {
        Args: {
          p_member: string;
          p_binding: string;
          p_action: string;
          p_data: Json;
        };
        Returns: Json;
      };
      research_rank: {
        Args: {
          p_member: string;
        };
        Returns: string;
      };
      research_snapshot: {
        Args: {
          p_member: string;
        };
        Returns: Json;
      };
      research_snapshot_v2: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      research_snapshot_v3: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      research_snapshot_v3_base: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      research_snapshot_v3_text: {
        Args: {
          p_member: string;
          p_binding: string;
          p_room?: string;
        };
        Returns: Json;
      };
      research_use_qualifies: {
        Args: {
          p_use: string;
        };
        Returns: boolean;
      };
      reserve_invitation_otp: {
        Args: {
          p_token_hash: string;
          p_email: string;
          p_cooldown_seconds?: number;
          p_max_requests?: number;
        };
        Returns: boolean;
      };
      wallet_proof_clock: { Args: Record<string, never>; Returns: string };
    };
    Enums: {
      member_role: "reviewer" | "steward" | "issuer";
      operation_status:
        "created" | "signed" | "broadcast" | "confirmed" | "reverted";
    };
    CompositeTypes: Record<never, never>;
  };
};
