import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createTestDatabase } from "../tests/database/database";

const db = await createTestDatabase();
try {
  const enums = (
    await db.query<{ name: string; labels: string[] }>(`
    select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as labels
    from pg_type t join pg_enum e on e.enumtypid = t.oid
    where t.typnamespace = 'public'::regnamespace group by t.typname order by t.typname
  `)
  ).rows;
  const enumNames = new Set(enums.map((entry) => entry.name));
  function typeFor(type: string): string {
    if (enumNames.has(type))
      return `Database["public"]["Enums"][${JSON.stringify(type)}]`;
    if (
      [
        "text",
        "uuid",
        "timestamp with time zone",
        "character varying",
        "uint256_decimal",
      ].includes(type)
    )
      return "string";
    if (
      ["integer", "bigint", "smallint", "numeric", "double precision"].includes(
        type,
      )
    )
      return "number";
    if (type === "boolean") return "boolean";
    if (["json", "jsonb"].includes(type)) return "Json";
    throw new Error(`Unmapped database type: ${type}`);
  }
  const tables = (
    await db.query<{ name: string }>(
      "select tablename as name from pg_tables where schemaname = 'public' order by tablename",
    )
  ).rows;
  const lines = [
    "// Generated by pnpm db:types from the migrated PostgreSQL catalog. Do not edit.",
    "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
    "export type Database = { public: { Tables: {",
  ];
  for (const table of tables) {
    const columns = (
      await db.query<{
        name: string;
        type: string;
        nullable: boolean;
        optional: boolean;
      }>(
        `
      select a.attname as name, format_type(a.atttypid, null) as type,
        not a.attnotnull as nullable, (a.atthasdef or not a.attnotnull) as optional
      from pg_attribute a where a.attrelid = $1::regclass and a.attnum > 0 and not a.attisdropped order by a.attnum
    `,
        [`public.${table.name}`],
      )
    ).rows;
    lines.push(`${JSON.stringify(table.name)}: {`);
    for (const mode of ["Row", "Insert", "Update"]) {
      lines.push(`${mode}: {`);
      for (const column of columns) {
        const optional =
          mode === "Update" || (mode === "Insert" && column.optional);
        lines.push(
          `${JSON.stringify(column.name)}${optional ? "?" : ""}: ${typeFor(column.type)}${column.nullable ? " | null" : ""};`,
        );
      }
      lines.push("};");
    }
    const relations = (
      await db.query<{
        name: string;
        columns: string[];
        referenced: string;
        referenced_columns: string[];
        one_to_one: boolean;
      }>(
        `
      select c.conname as name, r.relname as referenced,
        exists(select 1 from pg_index i where i.indrelid = c.conrelid and i.indisunique and i.indpred is null
          and i.indkey::smallint[] @> c.conkey and c.conkey @> i.indkey::smallint[]) as one_to_one,
        array(select a.attname from unnest(c.conkey) with ordinality k(num, ord) join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.num order by k.ord) as columns,
        array(select a.attname from unnest(c.confkey) with ordinality k(num, ord) join pg_attribute a on a.attrelid = c.confrelid and a.attnum = k.num order by k.ord) as referenced_columns
      from pg_constraint c join pg_class r on r.oid = c.confrelid
      where c.conrelid = $1::regclass and c.contype = 'f' and r.relnamespace = 'public'::regnamespace order by c.conname
    `,
        [`public.${table.name}`],
      )
    ).rows;
    lines.push("Relationships: [");
    for (const relation of relations) {
      lines.push(
        `{ foreignKeyName: ${JSON.stringify(relation.name)}; columns: ${JSON.stringify(relation.columns)}; isOneToOne: ${relation.one_to_one}; referencedRelation: ${JSON.stringify(relation.referenced)}; referencedColumns: ${JSON.stringify(relation.referenced_columns)}; },`,
      );
    }
    lines.push("];", "};");
  }
  lines.push("}; Views: Record<never, never>; Functions:");
  const functions = (
    await db.query<{
      name: string;
      result: string;
      args: { name: string; type: string; optional: boolean }[];
    }>(`
    select p.proname as name, format_type(p.prorettype, null) as result,
      coalesce((select jsonb_agg(jsonb_build_object('name', p.proargnames[i], 'type', format_type(p.proargtypes[i-1], null), 'optional', i > p.pronargs - p.pronargdefaults) order by i)
        from generate_series(1, p.pronargs) i), '[]'::jsonb) as args
    from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind = 'f' and p.prorettype <> 'trigger'::regtype order by p.proname
  `)
  ).rows;
  lines.push(functions.length ? "{" : "Record<never, never>");
  for (const fn of functions) {
    lines.push(`${JSON.stringify(fn.name)}: { Args: {`);
    for (const arg of fn.args)
      lines.push(
        `${JSON.stringify(arg.name)}${arg.optional ? "?" : ""}: ${typeFor(arg.type)};`,
      );
    lines.push(`}; Returns: ${typeFor(fn.result)}; };`);
  }
  lines.push(functions.length ? "}; Enums: {" : "; Enums: {");
  for (const entry of enums)
    lines.push(
      `${JSON.stringify(entry.name)}: ${entry.labels.map((label) => JSON.stringify(label)).join(" | ")};`,
    );
  lines.push("}; CompositeTypes: Record<never, never>; }; };", "");
  const { format } = await import("prettier");
  const generated = await format(lines.join("\n"), { parser: "typescript" });
  const destination = new URL("../src/types/database.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (
      (await readFile(destination, "utf8")).replaceAll("\r\n", "\n") !==
      generated
    )
      throw new Error("Database types are stale. Run pnpm db:types.");
    console.log("Database types match the migrations.");
  } else {
    await mkdir(new URL("../src/types/", import.meta.url), { recursive: true });
    await writeFile(destination, generated);
    console.log("Generated src/types/database.ts");
  }
} finally {
  await db.close();
}
