// Operator seed only. Every persona, claim and review remains visibly illustrative.
import { createClient } from "@supabase/supabase-js";
import { readFile } from "node:fs/promises";
import { illustration } from "../src/research/illustration";
import type { Database, Json } from "../src/types/database";
if (!process.argv.includes("--apply-demo"))
  throw new Error(
    "Requires --apply-demo. This seeds fictional research, not real expert outcomes.",
  );
const db = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SECRET_KEY!,
  { auth: { persistSession: false } },
);
const fixtures = JSON.parse(
  await readFile(
    new URL("../.local/research-fixtures.json", import.meta.url),
    "utf8",
  ),
) as { member: string; email: string; specialty: string }[];
for (const f of fixtures) {
  if (
    !/^grindly-qa-research-(project|risk|operations)@example.test$/.test(
      f.email,
    )
  )
    throw new Error("Only isolated fixtures may be seeded");
  const p = await db
    .from("research_profiles")
    .select("is_demo")
    .eq("member_id", f.member)
    .single();
  if (p.error || !p.data?.is_demo)
    throw new Error("Immutable demo label required");
}
async function mutate(member: string, action: string, data: Json) {
  const r = await db.rpc("research_mutate", {
    p_member: member,
    p_action: action,
    p_data: data,
  });
  if (r.error) throw new Error(r.error.message);
  return r.data as { id: string };
}
const messages: string[] = [];
for (const sample of illustration) {
  const f = fixtures.find((f) => f.specialty === sample.specialty)!;
  const body = `ILLUSTRATIVE SCENARIO: ${sample.claim} ${sample.limitation}`;
  const prior = await db
    .from("discussion_messages")
    .select("id")
    .eq("author_id", f.member)
    .eq("body", body)
    .maybeSingle();
  if (prior.error) throw prior.error;
  messages.push(
    prior.data?.id ??
      (
        await mutate(f.member, "message", {
          body,
          sources: [{ label: "Reference source", url: sample.source }],
          reply: messages.at(-1) ?? null,
        })
      ).id,
  );
}
const records: {
  id: string;
  version: string;
  author: string;
  specialty: string;
}[] = [];
for (const [index, sample] of illustration.entries()) {
  const f = fixtures.find((f) => f.specialty === sample.specialty)!;
  const claim = `ILLUSTRATIVE SCENARIO: ${sample.claim}`;
  const prior = await db
    .from("finding_versions")
    .select("id,finding_id")
    .eq("claim", claim)
    .maybeSingle();
  if (prior.error) throw prior.error;
  const id =
    prior.data?.finding_id ??
    (
      await mutate(f.member, "submit", {
        finding: null,
        previous: null,
        visibility: "members",
        specialty: sample.specialty,
        claim,
        sources: [{ label: "Reference source", url: sample.source }],
        addition: `ILLUSTRATIVE: ${sample.added}`,
        limitations: sample.limitation,
        observedAt: new Date().toISOString(),
        sourceMessage: messages[(index + 2) % 3]!,
        relatedVersion: records.at(-1)?.version ?? null,
        correction: null,
      })
    ).id;
  const finding = await db
    .from("findings")
    .select("current_version,status")
    .eq("id", id)
    .single();
  if (finding.error || !finding.data.current_version)
    throw new Error("Demo finding missing");
  const version = finding.data.current_version;
  if (finding.data.status === "pending") {
    const assignment = await db
      .from("review_assignments")
      .select("id,reviewer_id")
      .eq("version_id", version)
      .is("completed_at", null)
      .single();
    if (
      assignment.error ||
      !fixtures.some((f) => f.member === assignment.data.reviewer_id)
    )
      throw new Error("Isolated independent demo reviewer required");
    await mutate(assignment.data.reviewer_id, "review", {
      version,
      assignment: assignment.data.id,
      decision: "accept",
      reason:
        "ILLUSTRATIVE fixture decision generated by the demo seed to demonstrate scope and attribution, not an actual expert assessment.",
      conflicts: "Synthetic QA personas only; no real-world review claimed.",
      conflictFree: true,
    });
  }
  records.push({ id, version, author: f.member, specialty: sample.specialty });
}
for (const [index, r] of records.entries()) {
  const recipient = fixtures.find(
    (f) => f.specialty === records[(index + 1) % 3]!.specialty,
  )!;
  await mutate(recipient.member, "useful", {
    version: r.version,
    detail: `ILLUSTRATIVE: ${illustration[index]!.use} Fictional example, not evidence of real adoption.`,
  });
}
console.log(
  JSON.stringify({
    demo: true,
    records: records.map((r) => ({ id: r.id, specialty: r.specialty })),
    note: "Seeded fictional scenario; not live human review or customer validation.",
  }),
);
